spring:
  profiles:
    include:
      - openapi
  main:
    web-application-type: none
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    url: ${HM_DB_URL}
    username: ${HM_DB_USERNAME}
    password: ${HM_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
