spring:
  profiles:
    include:
      - common
      - openapi
      - slack
  main:
    web-application-type: none
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    url: ${HM_DB_URL}
    username: ${HM_DB_USERNAME}
    password: ${HM_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    kr.co.houmuch: INFO
